name: Pipeline E2E tests with Docker

on:
  push:
    branches:
      - docker_implem
  pull_request:
    branches:
      - docker_implem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build application 
        run: echo "Simulating application build..." && mkdir -p build && echo "App version 1.0.0" > build/my_app_info.txt
      - name: Upload application build artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-build
          path: build/

  run_e2e_tests:
    runs-on: ubuntu-latest
    services:
      selenium-hub:
        image: selenium/hub:latest
        ports: 
          - '4444:4444'

      selenium-node-chrome:
        image: selenium/node-chrome:latest
        # Luanch 
    steps:
      # All your regular steps go here...
      - name: Checkout code
        uses: actions/checkout@v4

      # ...and your test runner container will connect to these services
      - name: Build and Run Tests
        run: echo "I will build and run tests here!"
      
    